import { describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import * as BugPlatformAutofix from '../src/index.ts'

describe('bug-platform-autofix plugin', () => {
  it('exports an empty inject list and selection helpers', () => {
    expect(BugPlatformAutofix.inject).toEqual([])
    expect(BugPlatformAutofix.name).toBe('bug-platform-autofix')
    expect(typeof BugPlatformAutofix.loadMenuMapping).toBe('function')
    expect(typeof BugPlatformAutofix.loadOperatorConfig).toBe('function')
    expect(typeof BugPlatformAutofix.resolveMenu).toBe('function')
    expect(typeof BugPlatformAutofix.selectTickets).toBe('function')
    expect(typeof BugPlatformAutofix.loadState).toBe('function')
    expect(typeof BugPlatformAutofix.saveState).toBe('function')
    expect(typeof BugPlatformAutofix.isActive).toBe('function')
    expect(BugPlatformAutofix.TicketStateStore).toBeTypeOf('function')
    expect(typeof BugPlatformAutofix.assertProductBranch).toBe('function')
    expect(typeof BugPlatformAutofix.assertClean).toBe('function')
    expect(typeof BugPlatformAutofix.createBugfixBranch).toBe('function')
    expect(typeof BugPlatformAutofix.commitAll).toBe('function')
    expect(typeof BugPlatformAutofix.pushBranch).toBe('function')
    expect(typeof BugPlatformAutofix.listChangedFiles).toBe('function')
    expect(typeof BugPlatformAutofix.createMergeRequest).toBe('function')
    expect(BugPlatformAutofix.GitlabTokenMissingError).toBeTypeOf('function')
    expect(typeof BugPlatformAutofix.buildAgentBrief).toBe('function')
    expect(typeof BugPlatformAutofix.resolveForcedSkills).toBe('function')
    expect(typeof BugPlatformAutofix.loadManifest).toBe('function')
    expect(typeof BugPlatformAutofix.assertGlobalSkillsRunnable).toBe('function')
    expect(typeof BugPlatformAutofix.createDefaultAgentRunner).toBe('function')
    expect(typeof BugPlatformAutofix.renderHeadlessSkillPatch).toBe('function')
    expect(typeof BugPlatformAutofix.resolvePersonalSkillPluginPath).toBe('function')
    expect(typeof BugPlatformAutofix.runOneTicket).toBe('function')
    expect(typeof BugPlatformAutofix.runBatch).toBe('function')
    expect(typeof BugPlatformAutofix.assessNeedFrontendFix).toBe('function')
    expect(typeof BugPlatformAutofix.parseEligibilityModelText).toBe('function')
    expect(typeof BugPlatformAutofix.inspectWorkspace).toBe('function')
    expect(typeof BugPlatformAutofix.inspectAutofixWorkspaces).toBe('function')
    expect(typeof BugPlatformAutofix.loadLessonIndex).toBe('function')
    expect(typeof BugPlatformAutofix.loadAcceptedLessonBodies).toBe('function')
    expect(typeof BugPlatformAutofix.tryDraftLessonAfterDone).toBe('function')
    expect(typeof BugPlatformAutofix.pullLessonsFf).toBe('function')
  })

  it('accepts fully defaulted Config in apply', () => {
    const config = BugPlatformAutofix.Config({})
    expect(() => BugPlatformAutofix.apply(new Context(), config)).not.toThrow()
    expect(config.mappingFile).toBe('')
  })
})
